name: App Tests

on:

push:

branches:

- main

jobs:

deploy:

runs-on: ubuntu-latest

name: Test

steps:

- uses: actions/checkout@v3

- uses: bahmutov/npm-install@v1

- run: npm run lint (Run ESLint)

- run: npm run test (Run Jest)
